# TODO: TER CERTEZA DE QUE BACKEND RODA ANTES DE FRONTEND

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=8080
    volumes:
      - ./backend:/usr/src/backend
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - PORT=80
    volumes:
      - ./frontend:/usr/src/frontend
    depends_on:
      - backend
